### ISSUE TITLE
Create better error reporting / handling for bad .jbrowse file loading into desktop

### ISSUE THREAD

**Issue by carolinebridge-oicr** [GMOD/jbrowse-components#3944] opened 2023-09-22 19:37 UTC
It can be difficult as a user to understand why a .jbrowse file (jbrowse_config.json) is not being loaded into the desktop application. I have found that most .json syntax errors result in the error messaging reading "no assemblies found," which is incorrect. 

Bad configs can also just dump the mobx-state-tree error in the error message.

I am wondering if we can bolster our error reporting for this user-facing operation to be more readable, or diagnosable. Perhaps identify the "bad" slot from the config and report that to the user, e.g. "there's something wrong with your config, and it's around <here>."

Could also write up some user guides on debugging what could be wrong with a config, how to save a bad config, etc.

**Comment by cmdcolin** [comment] 2023-09-26 15:34
the overall goal of improving error messages is probably related to https://github.com/GMOD/jbrowse-components/issues/3226

**Comment by cmdcolin** [comment] 2023-09-26 15:38
the error messages actually do report accurate information but are often very verbose so it drowns out the useful info. we have some code here https://github.com/GMOD/jbrowse-components/blob/119226b37b6c367a2f7e8d137ad7a55dbe6e4ecc/packages/core/ui/ErrorMessage.tsx#L3-L29 that tries to extract the useful parts of the error but could probably be improved.

the alternative that i had considered is that every single MST type has an associated json schema or zod or something type system, and then rely on those systems to provide the better error message.

**Comment by cmdcolin** [comment] 2023-09-28 18:34
probably dupe of #3226

**Comment by cmdcolin** [comment] 2023-09-28 18:35
@carolinebridge-oicr

**Comment by cmdcolin** [comment] 2023-09-28 18:36
noticed that you mention some desktop specific  behavior like the no assemblies found, @carolinebridge-oicr if you want to submit a fix to improve the errors you are seeing that would be great. the other stuff about better error messages is probably the realm of #3226 though

**Comment by cmdcolin** [comment] 2023-10-03 18:37
After #3953, I think the remainder of issues may be related to general improving MST error stuff

**Closed by cmdcolin** 2023-10-03 18:37 UTC
Labels: enhancement
