### ISSUE TITLE
assemblies need karyotypes

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#832] opened 2020-02-14 18:54 UTC
* make assemblies able to have an optional karyotype adapter similar to how they have sequence adapters
* support one or two popular karyotype formats. probably just use whatever IGV uses.
* draw karyotypes in the overview ruler of the LGV, if the assembly has a karyotype

**Comment by cmdcolin** [comment] 2020-05-13 03:09
Probably a dupe of #530

**Comment by rbuels** [comment] 2020-05-13 03:14
Well it's not completely a dupe, this issue is more about the data adapter
for karyotypes and their place in the configuration, whereas #530 is about
displaying it. Maybe they should be folded together

**Comment by cmdcolin** [comment] 2020-05-13 03:29
I figured that ya, any effort to display them will involve adapting that datatype. It should be a pretty simple datatype it's like a special BED type thing.

**Comment by rbuels** [comment] 2020-05-13 03:32
why don't we groom these two on friday

**Comment by cmdcolin** [comment] 2022-02-18 22:29
basically done by #2267

**Closed by cmdcolin** 2022-02-18 22:29 UTC
Labels: enhancement, needs review
