### ISSUE TITLE
Make JBrowse capable of loading files that are drag and dropped into it

### ISSUE THREAD

**Issue by carolinebridge-oicr** [GMOD/jbrowse-components#3136] opened 2022-08-12 17:36 UTC
Probably doable for both desktop and web -- conceptualized as a desktop feature.

It might be convenient for users to be able to drag and drop their files directly into a running JBrowse session (desktop app or web). Could use guesser methods to either try to directly load the track into the JBrowse session or open the add track widget pre-loaded with the file populated.

**Comment by cmdcolin** [comment] 2022-09-01 17:12
possible dupe of (very old) issue here https://github.com/GMOD/jbrowse-components/issues/255

**Comment by cmdcolin** [comment] 2022-12-06 20:27
close as dupe

**Closed by cmdcolin** 2022-12-06 20:27 UTC
Labels: enhancement
