### ISSUE TITLE
Jbrowse 2.7.0 crash

### ISSUE THREAD

**Issue by tobyjhunt** [GMOD/jbrowse-components#3979] opened 2023-10-12 14:48 UTC
I was running the previous desktop JBrowse version on Ubuntu (22.04.3 LTS) with no issues. However having updated to 2.7.0 JBrowse is now crashing every time I try to open it with the following error message:

toby@ubu20-n-91c8254442:~/Documents/jbrowse$ ./jbrowse-desktop-v2.7.0-linux.AppImage 
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Checking for update
Checking for update...
Update for version 2.7.0 is not available (latest version: 2.7.0, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
[14210:1012/154054.972040:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[14210:1012/154058.090432:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[14210:1012/154102.405344:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!

Is this a bug with the new JBrowse version or an issue with something else on my laptop?

Many thanks for your help,

Toby.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version:**

2.7.0

If you're using the desktop version, tell us what OS are you using (e.g. MacOS
Catalina).

Ubuntu 22.04.3 LTS

If you're using the web version, tell us what browser you are using (e.g.
Chrome)
-->

**Additional context**

**Comment by cmdcolin** [comment] 2023-10-12 14:58
the vsync could be a red herring. if there is some sort of crash, it may be something else, as that thread seems to indicate that people can still run their apps fine, they just get those console messages

**Comment by tobyjhunt** [comment] 2023-10-12 15:00
Hello,

many thanks for the quick reply! I did wonder about redownloading the old
version but couldn't find it, could you provide a link?

Cheers,

Toby.

**Comment by cmdcolin** [comment] 2023-10-12 15:45
the AppImage for the last version before v2.7.0 is v2.6.3 and is available here https://github.com/GMOD/jbrowse-components/releases/tag/v2.6.3

**Comment by cmdcolin** [comment] 2023-10-12 15:50
I will try and see if I can test Ubuntu 22. If you have a screen recording video of this happening i'd be curious also. I don't think that "devtools" are available in the production builds of JBrowse Desktop currently which could help access any javascript errors. I will see if we can enable that for our next release...

**Comment by tobyjhunt** [comment] 2023-10-13 08:17
Hi Colin,

I can confirm that v2.6.3 works absolutely fine and as expected. Upon
opening I get prompted to
update to the new version (which is what I did yesterday) as per the
screenshot below. However if I click 'no' I can load up a session and
navigate around as normal.

[image: Screenshot from 2023-10-13 08-56-06.png]

Attempting to open up v2.7.0 still throws the same errors though. As
requested please find a screen recording here:

https://drive.google.com/file/d/1-e19laQ4YNc6grk9mPbE1bFCvEAWIGdW/view?usp=sharing

As you can see the homepage initially loads up but when I mouse click into
the window it goes blank and remains unresponsive. This throws up the first
of the vsync errors. A new vsync error is recorded every time I mouse click
between the terminal and the Jbrowse window. After the 3rd time no more
vsync errors are displayed no matter how many more times I navigate between
windows.

I hope this is of some help.

Cheers,

Toby.

**Comment by cmdcolin** [comment] 2023-10-13 21:23
thanks so much for the screen recording. i'm still not exactly sure what the issue is but a similar issue reported here...

https://github.com/bitwarden/clients/issues/6560

will keep an eye on this!

**Comment by cmdcolin** [comment] 2023-10-13 21:39
people in this thread https://github.com/electron/electron/issues/32760 suggest maybe downgrading to electron 25 may help. we upgraded from electron 25 to 26 between v2.6.3 and v2.7.0

**Comment by cmdcolin** [comment] 2023-10-13 22:40
@tobyjhunt would you be able to test this AppImage that i uploaded to google drive? it is the same code as v2.7.0 essentially but uses electron v25 instead of v26

here is a link

https://drive.google.com/file/d/1RCHnHhgj0hlsRtusj3eKOs_6CnUZAQbq/view?usp=sharing

**Comment by tobyjhunt** [comment] 2023-10-18 08:41
Hi Colin,

yep, can confirm that this version (v2.7.1-prerelease.2) also seems to work
absolutely fine on Ubuntu 22. Obviously electron 26 was the spanner in the
works!

Cheers,

Toby.

**Comment by tobyjhunt** [comment] 2023-10-18 13:09
Hi Colin,

I've just noticed that while the JBrowse GUI appears to be working fine
with this new version, I get the following errors in my terminal, including
the vsync issues that I saw with the original crashing - please see below.

Cheers,

Toby.

***@***.***:~/Documents/jbrowse$
> ./jbrowse-desktop-v2.7.1-prerelease.2-linux.AppImage
> Checking for update
> Checking for update...
> Error: Error: No published versions on GitHub
>     at newError
> (/tmp/.mount_jbrowsks3IYd/resources/app.asar/node_modules/builder-util-runtime/out/index.js:47:19)
>     at GitHubProvider.getLatestVersion
> (/tmp/.mount_jbrowsks3IYd/resources/app.asar/node_modules/electron-updater/out/providers/GitHubProvider.js:94:55)
>     at process.processTicksAndRejections
> (node:internal/process/task_queues:95:5)
>     at async AppImageUpdater.getUpdateInfoAndProvider
> (/tmp/.mount_jbrowsks3IYd/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:319:19)
>     at async AppImageUpdater.doCheckForUpdates
> (/tmp/.mount_jbrowsks3IYd/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:333:24)
> Error in auto-updater: Error: No published versions on GitHub
> (node:134714) UnhandledPromiseRejectionWarning: Error: No published
> versions on GitHub
>     at newError
> (/tmp/.mount_jbrowsks3IYd/resources/app.asar/node_modules/builder-util-runtime/out/index.js:47:19)
>     at GitHubProvider.getLatestVersion
> (/tmp/.mount_jbrowsks3IYd/resources/app.asar/node_modules/electron-updater/out/providers/GitHubProvider.js:94:55)
>     at process.processTicksAndRejections
> (node:internal/process/task_queues:95:5)
>     at async AppImageUpdater.getUpdateInfoAndProvider
> (/tmp/.mount_jbrowsks3IYd/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:319:19)
>     at async AppImageUpdater.doCheckForUpdates
> (/tmp/.mount_jbrowsks3IYd/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:333:24)
> (Use `jbrowse-desktop --trace-warnings ...` to show where the warning was
> created)
> (node:134714) UnhandledPromiseRejectionWarning: Unhandled promise
> rejection. This error originated either by throwing inside of an async
> function without a catch block, or by rejecting a promise which was not
> handled with .catch(). To terminate the node process on unhandled promise
> rejection, use the CLI flag `--unhandled-rejections=strict` (see
> https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode).
> (rejection id: 1)
> [134751:1018/093741.827456:ERROR:gl_surface_presentation_helper.cc(260)]
> GetVSyncParametersIfAvailable() failed for 1 times!
> [134751:1018/093745.791434:ERROR:gl_surface_presentation_helper.cc(260)]
> GetVSyncParametersIfAvailable() failed for 2 times!
> [134751:1018/093745.799628:ERROR:gl_surface_presentation_helper.cc(260)]
> GetVSyncParametersIfAvailable() failed for 3 times!

**Comment by cmdcolin** [comment] 2023-10-18 20:09
awesome, thanks. I tried to add a little code to reduce the debug output in the console. maybe can optimistically close this issue for now. thanks for testing!

**Closed by cmdcolin** 2023-10-18 20:09 UTC
Labels: bug

**Comment by cmdcolin** [comment] 2023-10-18 21:28
v2.7.1 now released with electron v27, hopefully helps with this issue :)
