### ISSUE TITLE
The jbrowse2 BED data parser doesn't seem to work correctly with test BED data file test_data/volvox/volvox-bed12.bed that jbrowse2 is using

### ISSUE THREAD

**Issue by sxd8** [GMOD/jbrowse-components#4156] opened 2024-01-02 02:03 UTC
**Describe the bug**

The jbrowse2 BED data parser doesn't seem to work correctly with test BED data file test_data/volvox/volvox-bed12.bed that jbrowse2 is using as an example.

**To Reproduce**

**Expected behavior**

The expectations:
1. the reference sequence should be defines as 'ctgA' for all subfeatures
2. I expect that SHOW FEATURE SEQUENCE actually displays  the sequence of the each particular feature according to the start end positions of the feature in relating to stgA sequence.
3. I expect that CDS coordinates are calculated relative to  ctgA start coordinate
**Screenshots**

![image](https://github.com/GMOD/jbrowse-components/assets/103960073/5aa1604e-7269-4b6e-a72d-aa8630c0ad8d)

**Version:**.   I installed   jbrowse-web-v2.7.2.zip

**Additional context**

**Comment by cmdcolin** [comment] 2024-01-02 05:27
thanks for reporting. I can confirm it, and a bugfix is pending :)

**Comment by cmdcolin** [comment] 2024-01-02 05:32
@sxd8 if you want to try a bugfix branch, can use


`jbrowse create --branch fix_bed_refname newfolder` to get the beta branch

**Comment by cmdcolin** [comment] 2024-01-02 19:26
fixed by #4158

**Closed by cmdcolin** 2024-01-02 19:26 UTC
Labels: bug

**Comment by sxd8** [comment] 2024-01-02 20:34
Hi Colin,

Is this fix already released in main branch - or should I use the bug fix
branch?

Thanks for the fast fix!

Sergey

**Comment by cmdcolin** [comment] 2024-01-02 20:44
It is on the main branch now, so you can use "jbrowse create --nightly newdir" (which gets the main branch) instead of that specific bugfix branch. A official release with the fix should be made soon also

**Comment by sxd8** [comment] 2024-01-02 20:55
Thanks!

**Comment by cmdcolin** [comment] 2024-01-16 04:28
for BED12, i would just not add the column names and rely on the default parser

for a full breakdown of what you are seeing

basically what you are seeing is that, when you specify the column names, then it stops trying to use a 'normal' BED parser which would have detected that you are using BED12 type format, and then instead just treats everything as string, and so the error you are seeing is some problematic math on the blockStarts that weren't properly parsed properly since it didn't think it was BED12

 their are some heuristics that go into parsing BED properly, so we could try to fix it, but ultimately, i'd just not specify the column headers for the normal BED12 type format. if your ultimate goal is to not use BED12 but just some other custom columnnames, it might be fine also, because really all you see is blockStarts/chromStarts failing to parse properly

another thing you could try is converting to bigBed, bigBed is a format i actually like because the autoSql makes all the column names much more unambiguous than plaintext bed.

**Comment by sxd8** [comment] 2024-01-16 04:37
Interestingly enough I started looking at BigBed already because I noticed
that it has autoSql header  in it.
So -yes it looks like the best way for me is  to use bigBed format.

Thanks,

Sergey
