### ISSUE TITLE
Highlight views (e.g. show which view's track selector is open)

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#713] opened 2019-12-02 18:43 UTC
When there are two LGVs displayed, it can get hard to tell which one an open track selector applies to. We could highlight the view (using CSS outline?) that has an open track selector.

**Comment by garrettjstevens** [comment] 2019-12-02 18:49
Another idea is to have the ability for a display to be view-specific. Below mockup has a track selector for a view at the bottom of the view. Could maybe do on the side instead?

![image](https://user-images.githubusercontent.com/25592344/69986037-bab41e00-14f9-11ea-9e53-baaeed7392c9.png)

**Comment by cmdcolin** [comment] 2019-12-05 14:56
Sort of a random xref, the circos view track selector looks always gray or, IMO, disabled.

![track_selector](https://user-images.githubusercontent.com/6511937/70245140-98154580-1743-11ea-9ed8-6df568cc2152.png)


There was a small bugfix on master to the "selected" attribute of the toggle button but it still looks disabled by default

At the very least it does not match the LGV which is just a button. Xref #713

**Comment by cmdcolin** [comment] 2020-02-08 22:32
Maybe dupe of #751

**Closed by cmdcolin** 2020-02-08 22:32 UTC
Labels: enhancement, needs review
