### ISSUE TITLE
Drag-and-drop tracks cause crash of JBrowseLinearView

### ISSUE THREAD

**Issue by Akusem** [GMOD/jbrowse-components#1223] opened 2020-09-17 14:50 UTC
**Describe the bug**

When trying to change the order of tracks in JBrowseLinearView (like moving the variants tracks above the gene's one) the component crash when the mouse move above another track.

Two exceptions are thrown when crashing in the console: 
```js
Error: no containing view found
```
And
```js
[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[observerha]' Error: no containing view found
```
I've tried to reproduce the error in JBrowse-web and didn't get any crash. Maybe it's due to JBrowseLinearView expecting to be in another component/environment like in JBrowse-web ? 

**To Reproduce**

Code is based on course `Embedding JBrowse 2 in your website, BCC2020`

1. Import JBrowseLinearView through script tag like described [here](https://jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_03_simple_site#add-jbrowse).
2. Create a div with specific id.
3. Create assembly and tracks object like describe [here](https://jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_04_assemblies) and [here](https://jbrowse.org/jb2/docs/bcc2020_embedding_jbrowse_05_tracks)
4. Create an instance of JBrowseLinearView:
```js
      const genomeView = new JBrowseLinearView({
        container: document.getElementById("jbrowse_linear_view"),
        assembly,
        tracks,
        location: '1:35,507..48,359',
      });
```
4. Open two tracks
5. Try to move a tracks above another by drag an drop

**Version:**
Jbrowse-linear-view released on amazon S3 for the course `Embedding JBrowse 2 in your website, BCC2020`

**Comment by garrettjstevens** [comment] 2020-09-17 14:59
Duplicate of #1081

**Comment by garrettjstevens** [comment] 2020-09-17 15:00
Hi, thanks for the bug report! This is actually a duplicate of another issue we have, #1081, so you may want to subscribe to that issue to get notifications on updates.

**Closed by garrettjstevens** 2020-09-17 15:00 UTC
Labels: bug
