### ISSUE TITLE
assembly-based displayedRegions do not always populate on initial load

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#736] opened 2019-12-12 20:01 UTC
Steps to reproduce, in either web or desktop:

1. make a session with a single LGV displaying regions from a single assembly

refresh and restore the session, and oftentimes the displayedRegions from the LGV are not populated.

**Comment by rbuels** [comment] 2019-12-12 20:04
I think this might be a bug with the displayedRegions autorun in the sessionModel's afterAttach. If the .sequence member of the assemblyData is populated sometime after the assembly's entry in assemblyData is created, the autorun might not be rerunning

**Comment by cmdcolin** [comment] 2019-12-12 20:08
At least one case where this happens is pointing to 

http://localhost:3000/?config=test_data/config_chrom_sizes_test.json on the create_chrom_sizes branch


This happens because the grape disappears from the assemblyData on refresh somehow and is replaced by hg19 and hg38

**Comment by cmdcolin** [comment] 2019-12-12 20:08
This might be related to how config merging is taking place though

**Comment by cmdcolin** [comment] 2019-12-12 21:02
I fixed the above mentioned issue in the create_chrom_sizes branch is now fixed, it keeps the explicit ?config= in the URL since otherwise window.history.replaceState makes it go away


If there is a different issue with this, I think we need a reproducible use case

**Closed** 2019-12-13 20:02 UTC
Labels: bug
