### ISSUE TITLE
features reference other features that do not exist in the file

### ISSUE THREAD

**Issue by jasongallant** [GMOD/jbrowse-components#4468] opened 2024-06-21 17:56 UTC
I'm writing in with an odd behavior-- I'm using @jbrowse-react-linear-genome-view in a web app that I'm working on, loading gff files hosted on S3.

When I load the feature track, I get the error "features reference other features that do not exist in the file".   

here's the stack trace:

Error: some features reference other features that do not exist in the file (or in the same '###' scope). 

/projectpath/node_modules/@gmod/gff/src/parse.ts:227:1 (at Parser._emitAllUnderConstructionFeatures ()
/projectpath/node_modules/@gmod/gff/src/parse.ts:165:1 (at Parser.finish ()
/projectpath/node_modules/@gmod/gff/src/api.ts:498:1 (at Object.parseStringSync ()
/projectpath/node_modules/@jbrowse/plugin-gff3/esm/Gff3TabixAdapter/Gff3TabixAdapter.js:85:1 (at Gff3TabixAdapter.getFeaturesHelper ()
/projectpath/node_modules/@jbrowse/plugin-gff3/esm/Gff3TabixAdapter/Gff3TabixAdapter.js:39:1 (at async)

 I spent a long time examining the GFF file for issues between parent and child, but could find nothing.

- Interestingly, when I zoom to any point in the GFF, the models load with no problem.
- When I load the exact same file from the same S3 path in Jbrowse Desktop, I have no issue.

I have verified this happens using both Chrome and Safari.  Not sure what else to try.

**Comment by cmdcolin** [comment] 2024-06-25 18:43
I didn't mean to auto-close this issue. I just merged that one thing with dontRedispatch

I am trying to brainstorm, but i don't have too much concrete ideas.


- browser cache issue. could make sure to clear browser cache to make sure
- server side cache issue (this one can be affect if you use AWS cloudfront but i don't think you are in this case...it can just be a thing where the server side is returning old results and could e.g. cause some mismatch of the tbi and the gff.gz perhaps). could rename the files server side to try to fix that.
- some other server side issue...for example this previous issue you posted was quite weird to me and I couldn't fully understand the resulting invalid gzip behavior....could be additional add on things happening https://github.com/GMOD/jbrowse-components/issues/4431#issuecomment-2156273036
- something related to the s3 signed urls. can't really imagine what that would be. you mentioned it worked on desktop so it seems unlikely and I couldn't reproduce locally either pointing at the signed urls directly


as far as the code you posted above though, that seems probably fine. i know it's not super productive but if you want to do an office hours, might be able to live debug :) https://jbrowse.org/jb2/contact/

**Comment by cmdcolin** [comment] 2024-11-27 02:01
if this is still happening let me know. it is random trivia, but in the time since this issue, gff-js was replaced with a new package gff-nostream (https://github.com/cmdcolin/gff-nostream) that is simpler to reason about for reasons sort of unrelated to this issue (avoids node.js polyfills for browser) and i'd be surprised if it had any effect on this issue, but could try it with latest versions to see

**Comment by cmdcolin** [comment] 2024-11-27 02:02
(closed for now due to issue triaging for now, but can reopen if still happening!)

**Closed by cmdcolin** 2024-11-27 02:01 UTC
