### ISSUE TITLE
Possibly flaky CLI admin-server test

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1246] opened 2020-09-28 18:05 UTC
https://travis-ci.com/github/GMOD/jbrowse-components/builds/187061737

Have seen this one locally occasionally too

**Comment by elliothershberg** [comment] 2020-09-28 21:32
Weird, I'll take a look at this. I can't reproduce this locally on master. You see it intermittently?

**Comment by cmdcolin** [comment] 2020-09-28 21:37
it's pretty intermittent, but it is something i've seen locally, on travis-CI there

**Comment by elliothershberg** [comment] 2020-10-01 20:30
Should be fixed. Can re-open if it comes back.

**Closed by elliothershberg** 2020-10-01 20:30 UTC
Labels: bug, housekeeping
