### ISSUE TITLE
adding grid lines to synteny block trapizoids

### ISSUE THREAD

**Issue by scottcain** [GMOD/jbrowse-components#3002] opened 2022-06-03 18:51 UTC
**Is your feature request related to a problem? Please describe.**

When there are long blocks of synteny, it can be difficult to see what is going on at a lower level. For example, if you have a synteny block that is multiple genes long, it is hard to say what is going on at a gene structure level (ie, does this exon boundary correspond to that exon boundary).

**Describe the solution you'd like**

In GBrowse_syn, they have major and minor grid lines that help show where the alignments are on a low level.  Of course, this won't always be possible, if for instance, you have synteny based on blocks of proteins that are similar in more distant species and there is no real nucleotide alignment possible (so there would have to be some code-level decision making about whether to so grid lines or not). Anyway, here is a screenshot of what it looks like at WormBase:

<img width="857" alt="Screen Shot 2022-06-03 at 11 37 26 AM" src="https://user-images.githubusercontent.com/274751/171927011-0185bfa4-6789-49f8-a423-a0ccbbd7caa2.png">
https://wormbase.org/tools/synteny/mercator/?search_src=Cele;name=X:1050001..1150000

**Comment by cmdcolin** [comment] 2024-11-27 01:54
dupe of #4300

**Closed by cmdcolin** 2024-11-27 01:54 UTC
Labels: enhancement
