### ISSUE TITLE
Integration tests each need a separate file (?)

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#431] opened 2019-07-31 02:03 UTC
Right now we have the integration tests for jbrowse-web in JBrowse.test.js. I have been having a lot of trouble getting the tests to pass for #430, even where I don't feel like what I did really should affect some of the tests that aren't passing.

After doing a bunch of digging, I've found out that even though we're using `afterEach(cleanup)`, some of the tests are affecting other tests, so they're not isolated from each other. One concrete example is the menus. When you click on a menu title in the menu bar, such as "HELP", it opens the menu. The implementation of the menu in material-ui ends up using `ReactDOM.createPortal(menuStuff, document.body)`, which adds the menu to `document.body` at _the same level_ as the app, so it looks like:

```html
<body>
  <div>
    app stuff...
  </ div>
  <div>
    menu stuff...
  </ div>
</body>
```

`afterEach(cleanup)` then only cleans up the original `div` and not the new menu `div`. Also, since the only way to search for things in the menu is to search the whole body (since they're all at the root level), different tests that use then menus could end up finding things in menu `div`s that they didn't create.

We could try to work around this problem (maybe find some way to not use Popper from material-ui), but I get the feeling that this isn't the only cross-test contamination that's happening. It's just the first concrete example I was able to find. So, I think we need to run each integration test in isolation.

I've tried things like creating a new JSDOM document for each test, but can't find a way to have each test in the same file have a different global `document`. Thus to truly isolate the tests we may have to put each integration test in its own file.

**Comment by cmdcolin** [comment] 2019-07-31 02:46
For things like document.body, that is an interesting scenario but maybe it can be mocked. If possible, I'd like to maybe get a better handle on what is causing the errors that you are seeing on your test, for example whether it is localstorage, or something like this. I just think that what we have currently, while not perfect isolation, is consistent in behavior.

**Comment by cmdcolin** [comment] 2019-07-31 02:52
I will admit I have seen x-files level cross contamination between test failures, but that seems to be when I just don't have a good handle on things... when I do have a handle on things, it seems like I can make all the tests pass and it seems good that way...if in the interest of reducing cross contamination it is better to use complete isolation, we could do so, but I think it's worth understanding the failure cases that lead to these failures

**Comment by cmdcolin** [comment] 2019-07-31 16:09
If I put the config editor integration test last (not a good sign) and disable localstorage it is able to pass tests

https://github.com/GMOD/jbrowse-components/tree/save_load_session_mod

Didn't figure out how to properly mock localstorage so I literally just bypass the codepath to use localstorage

**Comment by garrettjstevens** [comment] 2019-08-05 23:01
I was able to get the tests passing without rearranging the order by overriding localStorage with mocks and disabling updating the URL.

I did some more testing regarding the createPortal and cleanup stuff, and it actually turns out that this may not be a problem. I still don't understand it entirely, but once I fixed the other problems, I couldn't get any cross-contamination between tests even when I tried.

One thing to consider is that jsdom does have localStorage, which is why the tests were cross-contaminating since they all were writing/reading the same localStorage. When I mocked localStorage it just basically overrode localStorage methods with no-ops. I couldn't figure out how to mock localStorage on a per-test basis (jest.spyOn [doesn't work with localStorage](https://github.com/facebook/jest/issues/6798)). Also, there is [still discussion](https://github.com/facebook/create-react-app/pull/6882) about the best way to mock localStorage (apparently jsdom didn't used to have localStorage, and when they added it it broke most people's way of mocking it). One limitation is that all the ways of doing it currently also mock sessionStorage as well, but that may not matter to us. So if we want to have tests that actually use localStorage we might have to put those in a separate file.

**Comment by cmdcolin** [comment] 2019-10-31 01:57
Ill close this for now. The root cause was uncaught promises in jest. We just want to avoid uncaught promises

I demonstrated how simply this can happen by just doing

test('thing under test', () =>
setTimeout(() => throw new Error('oh no'), 200)
)

and it failed the next random test instead of the thing under test

**Closed by cmdcolin** 2019-10-31 01:57 UTC
