### ISSUE TITLE
`set-default-session --tracks` generates incomplete session

### ISSUE THREAD

**Issue by heavywatal** [GMOD/jbrowse-components#2708] opened 2022-02-02 09:25 UTC
`set-default-session --tracks` generates tracks with minimal properties: "type" and "configuration":

```json
    "views": [
      {
        "id": "LinearGenomeView-12",
        "type": "LinearGenomeView",
        "tracks": [
          {
            "type": "QuantitativeTrack",
            "configuration": "monocot"
          },
          {
            "type": "AlignmentsTrack",
            "configuration": "zea_mays"
          },
```

This `config.json` results in a fatal error `TypeError: Cannot read properties of undefined (reading 'height')`.

**To Reproduce**

1. `jbrowse create`
2. `jbrowse add-assembly`
3. `jbrowse add-track`
4. `jbrowse set-default-session --tracks`
5. Open the configured app in a web browser.

**Expected behavior**

- App should allow unset properties like `height` and show tracks with some default values.
- `set-default-session` should set all the required properties.

**Screenshots**

<img width="472" alt="Screen Shot 2022-02-02 at 17 56 50" src="https://user-images.githubusercontent.com/1431267/152124098-00c4224c-8f1e-4b5d-86c8-cfb8e7e4332e.png">

**Version:**

`@jbrowse/cli/1.6.4 darwin-x64 node-v16.13.21`

**Additional context**

I am trying to automate jbrowse configuration to handle many different conditions and data. I hope everything can be done via CLI.

**Comment by cmdcolin** [comment] 2022-02-02 20:02
Hi there
I think this is indeed an issue, basically the code for set-default-session was created before we had the concept of "displays"

I outlined that we could fix this probably a couple ways. Probably for the time being, --tracks will not work

You could instead

a) Use File->Export session and load that file with `jbrowse set-default-session -s exported_session.json`
b) Use admin server to set the default session
c) Use URL linking to the session you want using the URL parameter API (newly released in 1.6.4) https://jbrowse.org/jb2/docs/urlparams/

**Comment by cmdcolin** [comment] 2022-02-02 20:03
For us to fix the --tracks parameter we will 
1) Fix the CLI behavior as is
2) Add some sort of "session spec" (behavior similar to how &tracks works in the URL bar) to the CLI

**Comment by heavywatal** [comment] 2022-02-03 02:45
Thank you for the suggestion for workaround. Now I have another problem that `admin-server` does not work with `--target` (or I am doing it wrong):

1. `npx jbrowse admin-server --target mytarget` prints navigation to the URL like `http://localhost:9090?adminKey=1q2w3e4r5t`, which opens `./config.json` not `mytarget/config.json`.
2. Adding `&config=mytarget%2Fconfig.json` to the URL leads to the correct page, but the server tries to save changes to the wrong place, `mytarget/mytarget/config.json`.

Could you tell me what is wrong? or should I file a new issue for this?

**Comment by cmdcolin** [comment] 2022-02-03 13:48
this is not a well documented behavior but you can use

```
npx jbrowse admin-server
```

in your jbrowse root directory, or make --out point at a root directory, not at the specific config, and then you can navigate to http://localhost:9090?adminKey=keyhere&config=mytarget/config.json

and it will write to root directory+'mytarget/config.json'

this behavior was added here just for reference https://github.com/GMOD/jbrowse-components/issues/2139

can try to improve docs for this a bit

**Comment by heavywatal** [comment] 2022-02-06 08:19
Thank you, `npx jbrowse admin-server` in the root and adding `&config=mytarget/config.json` worked.

But `--out/--target <root>` did not work, and a browser only shows "Cannot GET /". (Even if it works, IMHO, it slightly diminishes the consistency of `--target` option. It is shared among many subcommands, but it has a special meaning/usage for `admin-server`)

**Comment by cmdcolin** [comment] 2022-02-06 15:17
thanks for the continued patience with this. Indeed, --out was not working. I have proposed a fix that allows it to work in #2715 

also changes the name of the flag to be --root instead of --out/--target because it is indeed inconsistent, and since --out was not working anyways, hopefully the change is not disruptive.

**Comment by abretaud** [comment] 2022-02-17 16:45
Hi!
I've just encountered the same kind of problem while working on the [jbrowse2 galaxy tool](https://github.com/galaxyproject/tools-iuc/pull/3997): when displaying the result of the galaxy tool, I'd like the default session to display the assembly and a list of tracks.
My code modifies the config.json to do it but:
- I'm forced to add a display block with `height: 100` to avoid the error described above: it would be nice if jbrowse could guess a default display
- I always get the "Select assembly to view" dialog, unless I add a displayedRegions in the default session. The problem is that my code knows nothing about the content of the genome (contigs and their lengths): wouldn't it be possible to just make the default session open the assembly at a default location, wisely chosen by jbrowse?

Any thoughts on that? Not sure if it matches with the kind of "session spec" you are referring to above

**Comment by garrettjstevens** [comment] 2022-02-17 22:18
@abretaud The "session spec" solution would allow us to specify a reduced representation of the session that JBrowse interprets and loads. As an example, the same kind of JSON that you can use in a URL like is described [here](https://jbrowse.org/jb2/docs/urlparams/#session-spec) could be placed in a config file.

@cmdcolin and I discussed some solutions for this today. If we want to be able to put a "session spec" in the config file, it would probably need its own key (like "defaultSessionSpec"). That does leave open the question of whether "defaultSession" or "defaultSessionSpec" would have priority if both were specified.

We also tried adding a snapshot preprocessor to the BaseTrackModel with the idea that we might be able to add displays on load, which would allow the current `set-default-session` code to work. The snapshot processors had some odd behavior, though. We tried `.preProcessSnapshot`, and for some reason the snapshot processer seemed to run ~20 on page load with only a single track open, and then several more times for each new track that was opened. We also tried using `types.snapshotProcessor`, but that caused the page to freeze when opening a new track.

**Comment by abretaud** [comment] 2022-02-22 08:45
Another related thing: is there (or could there be?) a way to specify some display settings for tracks that are not shown? For example, I'd like to add a bam track, hidden by default, but I would like it to use LinearSNPCoverageDisplay by default when the user shows it

**Comment by cmdcolin** [comment] 2022-02-23 18:56
@abretaud one way to force a SNPCoverage display by default is via the config file

our volvox sample config has an entry that does this that looks like this, the crucial part being the "displays" array

```
{
      "type": "AlignmentsTrack",
      "trackId": "volvox_cram_snpcoverage",
      "name": "volvox-sorted.cram (contigA, LinearSNPCoverageDisplay)",
      "assemblyNames": ["volvox"],
      "adapter": {
        "type": "CramAdapter",
        "cramLocation": {
          "uri": "volvox-sorted-altname.cram",
          "locationType": "UriLocation"
        },
        "craiLocation": {
          "uri": "volvox-sorted-altname.cram.crai",
          "locationType": "UriLocation"
        },
        "sequenceAdapter": {
          "type": "TwoBitAdapter",
          "twoBitLocation": {
            "uri": "volvox.2bit",
            "locationType": "UriLocation"
          }
        }
      },
      "displays": [
        {
          "type": "LinearSNPCoverageDisplay",
          "displayId": "volvox_cram_snpcoverage_snpcoverage"
        }
      ]
    },
```

https://jbrowse.org/code/jb2/v1.6.5/?config=test_data%2Fvolvox%2Fconfig.json&session=share-pwzCQXhz9F&password=fLJAO

**Comment by cmdcolin** [comment] 2022-03-18 17:28
@abretaud can you create a new issue or discussion for this?  it's hard to track too many branches on a thread :) 

just to try to address, I think displayCrossHatches is part of the "renderer" config. It is also part of the state model of the display to allow the user to select it via the UI. we could probably add it as a config of the display to make that easier

**Closed** 2024-01-10 17:53 UTC
Labels: bug
